### ISSUE TITLE
Update to JSON-LD 1.1

### ISSUE THREAD

**Issue by MattesWhite** [kianschmalenbach/rdf-browser#12] opened 2020-09-15 08:13 UTC
When I add `"@version": 1.1` to a JSON-LD context I get the following error:

```text
RDF-Browser: Error

The RDF-document could not be displayed properly.
The reason is displayed below:

jsonld.ProcessingModeConflict: @version: 1.1 not compatible with json-ld-1.0

Press Ctrl+U to view the page sources.
```

I guess this is a problem of a dependency. Maybe upgrading is already enough. However, It would be nice to have JSON-LD 1.1 support.

**Comment by kianschmalenbach** [comment] 2020-09-17 14:30
Hi,

I just pushed a new version to the develop branch where a [different JSON-LD parser](https://github.com/rubensworks/jsonld-streaming-parser.js) is used, which claims to support JSON-LD 1.1.

Could you please check if the issue is resolved with this version or provide a file that previously lead to the error you observed?
When I check with the file at [http://paul.ti.rw.fau.de/~yk05yhet/foo.jsonld](http://paul.ti.rw.fau.de/~yk05yhet/foo.jsonld), I get no error with either version of the plugin...

Cheers,
Kian

**Comment by kianschmalenbach** [comment] 2020-09-18 15:20
Hi,

The new JSON-LD parser is part of today's release 1.1.3, so installing from sources is no longer necessary.

I assume that using this parser should fix the issue; if you still encounter problems, please open a new one.

Cheers,
Kian

**Closed by kianschmalenbach** 2020-09-18 15:20 UTC
